spring.application.name=jiro-team
springdoc.swagger-ui.path=/swagger-ui
server.port=8089

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/jiro_team
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD}

app.url.user=http://localhost:8087/api/v2
app.url.task=http://localhost:8086/api/v3